export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG';
export const GET_DS_LOAI_NGUOI_DUNG = 'GET_DS_LOAI_NGUOI_DUNG';
export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_SEARCH = 'GET_USER_SEARCH';
export const GET_INFO_USER = 'GET_INFO_USER';
